### ISSUE TITLE
Run shell command to index tags from outside Emacs

### ISSUE THREAD

**Issue by foopang** [xcwen/ac-php#1]
Hi, I would like to know if it is possible run shell command to index tags from outside Emacs. Because when I run the command `ac-php-remake-tags` on a large project, it takes really long time and Emacs would just stuck, I can't edit any files or navigate away while the command is being executed.

**Comment by xcwen** [comment]
how many files in you project?!
you can set:

(setq ac-php-cscope nil)

to disable cscope gen file .  maybe ok.

**Comment by xcwen** [comment]
also you can reopen new emacs program . do this :>

**Comment by foopang** [comment]
My project is based on Symfony, it has many packages installed with Composer. I cannot successfully indexed the project. Sometimes it just failed the message: **Removing old name: no such file or directory**. Also, is there any way to exclude some files or folders from being indexed? Such as the cached PHP files generated by Symfony. Many thanks!

**Comment by xcwen** [comment]
exec at project root: at command line:

```
emacs -Q --script ~/.emacs.d/elpa/ac-php-*/ac-php-remake-tags-bat.el 
```

if won't   without cscope gen files

```
emacs -Q --script  ~/.emacs.d/elpa/ac-php-remake-tags-without-cscope-bat.el
```

**Comment by foopang** [comment]
Thanks! It works.

However, I get the following error:

```
rebuild /Site/vendor/phpoffice/phpexcel/Documentation/Examples/Reading WorkBook Data/exampleWorkBookReader01.php
phpctags ERROR:PHPParser: No File specified. - 
Removing old name: no such file or directory, /Site/.tags/tags_dir_foo/vendor-phpoffice-phpexcel-Documentation-Examples-Reading WorkBook Data-exampleWorkBookReader01.tags
```

Is it because of whitespace of the pathname `Reading WorkBook Data`? Can we set an exclusion pattern so that those files will be ignored?

**Comment by xcwen** [comment]
use  `ln -s ` link to project .
link this:
 
localhost:~/ac-php/phptest$ ./mktags.sh 
Source file `/home/jim/.emacs.d/elpa/ac-php-20150521.813/ac-php.el' newer than byte-compiled file
remake /home/jim/ac-php/phptest/
rebuild /home/jim/ac-php/phptest/Http/Cookies.php
rebuild /home/jim/ac-php/phptest/Http/Headers.php
rebuild /home/jim/ac-php/phptest/Http/Request.php
rebuild /home/jim/ac-php/phptest/Http/Response.php
rebuild /home/jim/ac-php/phptest/Http/Util.php
rebuild /home/jim/ac-php/phptest/a.php
rebuild /home/jim/ac-php/phptest/testa.php
rebuild /home/jim/ac-php/phptest/testb.php
rebuild cscope  data file 
BUILD SUCCESS.
localhost:~/ac-php/phptest$ ls -l Http
lrwxrwxrwx 1 jim jim 25  5月 22 10:52 Http -> /home/jim/Slim/Slim/Http/
localhost:~/ac-php/phptest$ ls
a.php  dir1  Http  mktags.sh  testa.php  testb.php
localhost:~/ac-php/phptest$

**Comment by xcwen** [comment]
```
rebuild /Site/vendor/phpoffice/phpexcel/Documentation/Examples/Reading WorkBook Data/exampleWorkBookReader01.php
phpctags ERROR:PHPParser: No File specified. - 
Removing old name: no such file or directory, /Site/.tags/tags_dir_foo/vendor-phpoffice-phpexcel-Documentation-Examples-Reading WorkBook Data-exampleWorkBookReader01.tags

```

now I fix this bug .

# 

```
Can we set an exclusion pattern so that those files will be ignored?
```

no suported.
you can change
    `(setq file-list (ac-php-find-php-files tags-dir "^[^#]+\\.php$" ) )`
in  `ac-php-remake-tags` function

**Comment by xcwen** [comment]
it is not good idea  mkdir `.tags` in `/Site/`

 you can copy other php libs into your project .  
itis only for ac-php complate .

**Comment by foopang** [comment]
Thanks for your help! I can finally index my project, but I am still not able to get auto-complete work for my project. Maybe I missed something for my project.

I also tried with your sample phptest files. It seems that auto-complete only works for class variables, I could not get auto-complete work for class methods either. Not sure what I did wrong.

**Comment by xcwen** [comment]
remake phptest tags and retest

**Comment by foopang** [comment]
I did remake the tags. But still no auto-complete for class methods.I am using your emacs config in https://github.com/xcwen/site-lisp
![untitled](https://cloud.githubusercontent.com/assets/4666757/7781792/341349c6-012a-11e5-8577-21a431cae21d.png)

**Comment by xcwen** [comment]
```
I also tried with your sample phptest files. It seems that auto-complete only works for class variables, I could not get auto-complete work for class methods either. Not sure what I did wrong.
```

i fix this bug .  
you can update and retest.

**Comment by foopang** [comment]
Great! Thank you so much!

**Comment by xcwen** [comment]
```
Can we set an exclusion pattern so that those files will be ignored?
```

now surported,   but use inclusion  pattern ^_^
more info at :
https://github.com/xcwen/ac-php#tags

**Comment by foopang** [comment]
Awesome! Thanks for that :+1: 

But I still get no auto-complete for class methods, and not sure why parent class variables don't have auto-complete now :( 

One more issue, when we set PHP Doc for the variable type as below, we have to save the file and rebuild PHP tags in order to make auto-complete available for the variable. I think if we can make auto-complete available immediately for the type defined in PHP Doc without needing to save the file and rebuilding tags would be really great!

```
/**
 * @var classtype
 */
public $v1;
```

**Comment by xcwen** [comment]
```
But I still get no auto-complete for class methods, and not sure why parent class variables don't have auto-complete now :( 
```

i fix some bugs . now , update and retest phptest

**Comment by xcwen** [comment]
where are you install  ac-php ?   melpa ??  clone ?!

**Comment by xcwen** [comment]
like this 
![2015-05-24 11 18 35](https://cloud.githubusercontent.com/assets/1539162/7786508/bbc4c6c4-0206-11e5-9333-c1a0276c11a5.png)

**Comment by foopang** [comment]
I use the latest git master.

![screen shot 2015-05-24 at 11 59 54 am](https://cloud.githubusercontent.com/assets/4666757/7786605/b24f200c-020c-11e5-9101-e8e781748b45.png)

**Comment by xcwen** [comment]
ok ,  copy your emacs config   send to me  
xcwenn@qq.com

**Comment by xcwen** [comment]
clean .tags and retest
rm -rf .tags/*

**Comment by foopang** [comment]
Not working after clean .tags and retest. This is my emacs config http://pastebin.com/yBwDXB5Z

**Comment by xcwen** [comment]
cat   ./tags/tags-data.el
cat /.tags/tags_dir_{youname}/testb.tags

**Comment by xcwen** [comment]
for clean emacs config test: 
https://github.com/xcwen/ac-php#test

**Comment by foopang** [comment]
tags-data.el:

```
(((#3="Test\\TestC" (("p" #1="v1" #1# "dir1/test c.php:11" "string" "Test\\TestC" "public") ("d" #2="DIR" #2# "dir1/test c.php:13" #6="" #3# #8="public"))) (#7="Test\\Testa" (("p" #4="v1" #4# "testa.php:11" "string" "Test\\Testa" "public") ("d" #5="DIR" #5# "testa.php:13" #6# #7# #8#))) (#10="Testb" (("p" #9="v2" #9# "testb.php:9" "\\Test\\Testa" #10# "public")))) (("c" "Test\\TestC" "Test\\TestC()" "dir1/test c.php:5") ("c" "Test\\Testa" "Test\\Testa()" "testa.php:5") ("c" #11="Testb" "Testb()" "testb.php:3")) ((#11# "test\\Testa")))
```

testb.tags:

```
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    techlivezheng   /techlivezheng@gmail.com/
!_TAG_PROGRAM_NAME      phpctags        //
!_TAG_PROGRAM_URL       https://github.com/techlivezheng/phpctags       /official site/
!_TAG_PROGRAM_VERSION   0.5.1   //
Testb   /Users/foopang/.emacs.d/site-lisp/ac-php/phptest/testb.php  /^class Testb  extends test\Testa{$/;"  c       line:3  inherits:test\Testa
get_tt  /Users/foopang/.emacs.d/site-lisp/ac-php/phptest/testb.php  /^    public function get_tt(){$/;"     m       line:20 class:Testb     access:public
get_v2  /Users/foopang/.emacs.d/site-lisp/ac-php/phptest/testb.php  /^    public function get_v2(){$/;"     m       line:16 class:Testb     access:public   type:Test\Testa
v2      /Users/foopang/.emacs.d/site-lisp/ac-php/phptest/testb.php  /^      public $v2;$/;" p       line:9  class:Testb     access:public   type:\Test\Testa
```

**Comment by xcwen** [comment]
(set ac-php-debug-flag t)

update and clean .tags  and retest
get me  logs from "_Message_" buffer.
like this:

```
[AC-PHP-DEBUG]:DO line:!_TAG_FILE_FORMAT    2   /extended format; --format=1 will not append ;" to lines/
[AC-PHP-DEBUG]:DO line:!_TAG_FILE_SORTED    1   /0=unsorted, 1=sorted, 2=foldcase/
[AC-PHP-DEBUG]:DO line:!_TAG_PROGRAM_AUTHOR techlivezheng   /techlivezheng@gmail.com/
[AC-PHP-DEBUG]:DO line:!_TAG_PROGRAM_NAME   phpctags    //
[AC-PHP-DEBUG]:DO line:!_TAG_PROGRAM_URL    https://github.com/techlivezheng/phpctags   /official site/
[AC-PHP-DEBUG]:DO line:!_TAG_PROGRAM_VERSION    0.5.1   //
[AC-PHP-DEBUG]:DO line:v2   /home/jim/ac-php/phptest/testb.php  /^  public $v2;$/;" p   line:9  class:Testb access:public   type:\Test\Testa
[AC-PHP-DEBUG]:Matching type[p]  
[AC-PHP-DEBUG]:DO line:get_v2   /home/jim/ac-php/phptest/testb.php  /^    public function get_v2(){$/;" m   line:16 class:Testb access:public   type:Test\Testa
[AC-PHP-DEBUG]:Matching type[m]  
[AC-PHP-DEBUG]:DO line:get_tt   /home/jim/ac-php/phptest/testb.php  /^    public function get_tt(){$/;" m   line:20 class:Testb access:public
[AC-PHP-DEBUG]:Matching type[m]  
```

**Comment by foopang** [comment]
OK, cool! Everything works fine now. Somehow I installed an older version of AC-PHP from MELPA I didn't uninstall it properly.

I just tested below for auto-complete of a class member which has no type defined, error messages showed.

```
/**  @var  $tb  Testb  */
$tb->get_v2()->get_v1()->
```

```
 class[Test\Testa]'s member[get_v1] not define type                                      
Error running timer `ac-update-greedy': (args-out-of-range "" 0 1)
 class[Test\Testa]'s member[get_v1] not define type 
Error running timer `ac-show-menu': (args-out-of-range "" 0 1)

```

**Comment by xcwen** [comment]
```
 class[Test\Testa]'s member[get_v1] not define type                                      
Error running timer `ac-update-greedy': (args-out-of-range "" 0 1)
 class[Test\Testa]'s member[get_v1] not define type 
Error running timer `ac-show-menu': (args-out-of-range "" 0 1)

```

I fix this bug ^_^
thanks

**Comment by foopang** [comment]
Thank you so much for fixing it so quickly!

Just found another problem with `use` statement. Now when extending a class with namespace we must use fully qualified class name such as `Test\Testa` in order to have auto-complete inherited from the parent class. Below code with `use` statement won't have auto-complete of the parent class. Any way to have this feature.

``` php
namespace Test;

use Test\Testa;

class Testb  extends Testa{
  // 
}
```

**Comment by xcwen** [comment]
``` php
namespace Test;

use Test\Testa;

class Testb  extends Testa{
  // 
}
```

i fix this bug.

**Comment by foopang** [comment]
WOW! You're truly amazing :+1:

It's very useful. Thanks a lot!

**Comment by foopang** [comment]
Sorry, still one little problem. When the parent class is using the same namespace, we don't necessarily need to explicitly declare it in `use` statement. However, AC-PHP won't recognize the parent class if we don't declare it in `use` statement or use fully qualified class name in `extends` statement.

**Comment by xcwen** [comment]
fix `parent is same namespace` bug .

**Comment by foopang** [comment]
Cool! It works for inherited class now :+1:

But it doesn't work for PHP Doc type definition when the namespace is omitted.

**Comment by xcwen** [comment]
fix

**Comment by foopang** [comment]
Perfect now. Thanks!
