### ISSUE TITLE
Remake tags asynchronously

### ISSUE THREAD

**Issue by kostajh** [xcwen/ac-php#10]
See for example how https://github.com/jorissteyn/edep (`M-x edep-phptags-index`) does it.Otherwise, indexing a large project locks up Emacs for several minutes.

**Comment by xcwen** [comment]
thank , let me see ^_^

**Comment by xcwen** [comment]
1:   https://github.com/xcwen/ac-php#configue-php-file-search
2:
you can use  cmdline   mktags ...  
copy  ac-php/phptest/mktags.sh  to you  project root.

# exec like this:

localhost:~/ac-php/phptest$ ./mktags.sh 

do remake /home/jim/ac-php/phptest/
 REBUILD: load file  modify time  start
 REBUILD:  rebuild file start
 REBUILD final start  
REBUILD SUCCESS 
localhost:~/ac-php/phptest$

**Comment by xcwen** [comment]
Remake tags asynchronously  is ok .. like edep
