### ISSUE TITLE
PHP Mode Integration

### ISSUE THREAD

**Issue by ejmr** [xcwen/ac-php#11]
[A recent discussion](https://github.com/ejmr/php-mode/issues/284) on the PHP Mode project page proposed the idea of integrating ac-php into PHP Mode.  That is, PHP Mode would "ship" with ac-php already included.  I'd like to hear your thoughts on this @xcwen before I do anything to make ac-php part of the PHP Mode package itself.

**Comment by xcwen** [comment]
it's a good idea.

**Comment by ejmr** [comment]
Agreed.  I just wanted to make sure you had no objections or anything.
