### ISSUE TITLE
ac-php not compatible with PHP 7.3?

### ISSUE THREAD

**Issue by gjm** [xcwen/ac-php#115]
Hi.

I'm getting errors with `ac-php-remake-tags` similar to this:

```
PHPParser: A trailing comma is not allowed here on line...
```

That error refers to a trailing comma in a multi-line function call, something that is supported by PHP 7.3. I've checked `ac-php-php-executable` and it point to `/usr/bin/php`, a PHP 7.3 executable, so I don't understand why I'm getting the parse errors. 

Is there something I'm doing wrong or missing?

I'm using `ac-php-core` as a dependency of `company-php`. Could this be related?

Thanks in advance.

**Comment by sergeyklay** [comment]
@gjm I'll try to sort out ASAP. Thank you for the report.

**Comment by xcwen** [comment]
show me test php code.

**Comment by gjm** [comment]
@xcwen what do you mean by test code?

I'm using ac-php as a backend to company. When it indexes my code I get the errors I posted in the OP.

**Comment by sergeyklay** [comment]
@xcwen  Something like this
```php
function ($a, $b, $c , ) // <-- notice: leading comma
{
    //
}
```

Is it correct @gjm ?

**Comment by gjm** [comment]
@sergeyklay @xcwen Yes just like that, except it's multi line:
```php
function (
    $a, 
    $b, 
    $c, 
)
{
    //
}
```

**Comment by sergeyklay** [comment]
Most likely it is [PHP-Parser](https://github.com/nikic/PHP-Parser) issue https://github.com/nikic/PHP-Parser/issues/598;

Example:

```php
<?php

use PhpParser\Error;
use PhpParser\NodeDumper;
use PhpParser\ParserFactory;

require __DIR__.'/vendor/autoload.php';

$code = <<<'CODE'
<?php

function test($foo, $bar,) // <-  A trailing comma
{
    var_dump($foo);
}
CODE;

$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
try {
    $ast = $parser->parse($code);
} catch (Error $error) {
    echo "Parse error: {$error->getMessage()}\n";
    return;
}

$dumper = new NodeDumper;
echo $dumper->dump($ast) . "\n";
```

```bash
$ php -v | head -n 1
PHP 7.3.0 (cli) (built: Jan  8 2019 18:55:14) ( ZTS DEBUG )
```

```bash
$ php parser.php 
Parse error: A trailing comma is not allowed here on line 3
```

**Comment by sergeyklay** [comment]
@gjm  Take a look at https://wiki.php.net/rfc/trailing-comma-function-calls

![image](https://user-images.githubusercontent.com/1256298/55832455-4bc72680-5b1e-11e9-9bd9-49733171e6a4.png)

**Comment by sergeyklay** [comment]
@gjm Fixed in `master` branch. Take a look at the PR: https://github.com/xcwen/ac-php/pull/117

**Comment by gjm** [comment]
@sergeyklay seems OK for me!
