### ISSUE TITLE
Not work in TRAMP

### ISSUE THREAD

**Issue by zonuexe** [xcwen/ac-php#13]
Hi

I am editing PHP code via [TRAMP](http://www.emacswiki.org/emacs/TrampMode).
ac-php works well with local file system, but ac-php In TRAMP is always freeze.

This problem is not only ssh/scp, occurs even `sudo`.
### How to reproduce
1. `M-x find-file /sudo::/your/project/target.php`
   - or use [find-file-as-sudo](https://gist.github.com/zonuexe/a5f81b5cb5cd4b44f577)
2. Input any character twice.
3. FREEEEEEEZE [o_O]

``` el
;; My environment is:
;; GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)
(defun my/buffer-in-tramp ()
  "Return non-nil if buffer file is in TRAMP."
  (and buffer-file-name
       (s-match
        (concat "\\`/" (regexp-opt (mapcar 'car tramp-methods)) ":")
        buffer-file-name)))

(defun my/php-mode-hook ()
  (when (require 'php-eldoc nil t)
    (php-eldoc-enable))
  (subword-mode t)
  (setq show-trailing-whitespace t)
  (c-set-style "psr2")
  ;; Do not use ac-php in tramp
  ;; (unless (my/buffer-in-tramp)
  ;;   (cl-pushnew 'ac-source-php ac-sources))
  (cl-pushnew 'ac-source-php ac-sources))

(add-hook 'php-mode-hook 'my/php-mode-hook)
```

thanks.

**Comment by xcwen** [comment]
brew install sshfs
use sshfs mount remotedir in localdir.

---

then you can edit them the same as local files

**Comment by journeylee** [comment]
same problem here.
the while loop in line1593 in ac-php-core.el cause dead loop if in tramp buffer, tags-dir never can be a "/", it will be "/sudo::/"

``` elisp
(defun ac-php-get-tags-dir  ()
  "DOCSTRING"
  (let (tags-dir tags-file) 
    (when (buffer-file-name) 
      (setq tags-dir (file-name-directory (buffer-file-name)  ))
    )

    (unless tags-dir
      (setq tags-dir ( expand-file-name  default-directory) ))

    (while (not (or
                 (file-exists-p  (concat tags-dir  ".ac-php-conf.json" ))
                 (file-exists-p  (concat tags-dir  ".tags" ))
                    (string= tags-dir "/") ))
      (setq tags-dir  ( file-name-directory (directory-file-name  tags-dir ) ) ))
    (if (string= tags-dir "/") (setq tags-dir nil )   )
    tags-dir
    ))
```

i change it to 

``` elisp
    (setq previouse-tags-dir "")
    (while (not (or
                 (file-exists-p  (concat tags-dir  ".ac-php-conf.json" ))
                 (file-exists-p  (concat tags-dir  ".tags" ))
                    (string= tags-dir "/") ))
      (progn
        (setq previouse-tags-dir tags-dir)
        (setq tags-dir  ( file-name-directory (directory-file-name  tags-dir ) ) )))      
```

it'll works like charm.

**Comment by xcwen** [comment]
give me  `ac-php-get-tags-dir`   all code

or commit request .

**Comment by webdevelopers-eu** [comment]
I have also problem using TAGS over TRAMP with HUGE project (around 1 mil of PHP lines).

Is it possible to build the TAGS locally using local copy/relative paths and then symlink .ac-php/LOCAL_PROJECT_NAME to .ac-php/TRAMP_REMOTE_PROJECT ? 

UPDATE: I just did the symlink :-D and It actually seems to work!

**Comment by xcwen** [comment]
why use TRAMP for edit php?!

**Comment by webdevelopers-eu** [comment]
:-) Not sure why that question. But out of curiosity: how else can you edit a PHP on the server that allows connections only from office-IPs and you need to sudo on top of it?

With TRAMP it is easy - tunnel connection from your home to the office and then connect from office to the server and sudo... Voila! Done.

And if you try to suggest local edits and GIT/SVN/CSV/... pushes to live server. You know, it all depends on the setup. We have very complicated cluster/nginx/memcached/network fs/db/live-data cloned devel sites/... setup that is impossible to reproduce locally on one machine so it is much better to develop on our develop server so you see immediately the real-world behavior. So TRAMP it! Doing it for years.
