### ISSUE TITLE
Support for local variables of type other than class instantiated objects?

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#14]
Does ac-php support all global scoped variables? Variables such as integers, or arrays, strings, etc that were not class instantiated objects.

e.g.:

``` php
<?php
$var = 1;

$v|
```

There is no autocompletion for `$var` at position `|`. 

I have run `ac-php-remake-tags`.

**Comment by xcwen** [comment]
no support .

**Comment by xcwen** [comment]
re test :>
