### ISSUE TITLE
phpctags does not compile with php5

### ISSUE THREAD

**Issue by quimm2003** [xcwen/ac-php#143]
Hi, phpctags does not compile when using php5. And so I've been forced to use php7.0 as ac-php php executable. Otherwise autocompletion in emacs does not work.

`quim:~/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/| php ./phpctags

PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Notice:  Undefined index: config-file in phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php on line 247
PHP Stack trace:
PHP   1. {main}() /home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags:0
PHP   2. include() /home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags:10
PHP Warning:  Unsupported declare 'strict_types' in phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php on line 1
PHP Stack trace:
PHP   1. {main}() /home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags:0
PHP   2. include() /home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags:10
PHP   3. PHPCtags->__construct() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php:258
PHP   4. spl_autoload_call() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php:40
PHP   5. Composer\Autoload\ClassLoader->loadClass() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php:40
PHP   6. Composer\Autoload\includeFile() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/vendor/composer/ClassLoader.php:322
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php on line 21
PHP Stack trace:
PHP   1. {main}() /home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags:0
PHP   2. include() /home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags:10
PHP   3. PHPCtags->__construct() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php:258
PHP   4. spl_autoload_call() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php:40
PHP   5. Composer\Autoload\ClassLoader->loadClass() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/bootstrap.php:40
PHP   6. Composer\Autoload\includeFile() phar:///home/quim/Applications/Emacs-26/.emacs.d/elpa-26.3/ac-php-core-20200516.52/phpctags/vendor/composer/ClassLoader.php:322
`

**Comment by xcwen** [comment]
not surport php5.

**Comment by xcwen** [comment]
not surport php5.
