### ISSUE TITLE
Support for PHP native enum

### ISSUE THREAD

**Issue by rotdrop** [xcwen/ac-php#152]
Hi there,

thanks again for this package! I have the impression that PHP native enums are not yet supported, e.g. things like this
```
enum FooBar: string {
   case FOO = 'bar';
   case BAR = 'foo';
}
```
I suppose that also phpctags would have to be changed?

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php/commit/35eeaa3aaf1a38b183783dc693012242c7dd2053
retest
update package and run `ac-php-remake-tag-all`
