### ISSUE TITLE
Bundled PHPCTAGS doesn't work when deprecation warnings are issued

### ISSUE THREAD

**Issue by flaviovs** [xcwen/ac-php#157]
The phpctags script bundled with ac-php generates lots of warnings when run under PHP 8.2 with the stock development  _php.ini_. Here's some messages:

```
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in phar:///home/flaviovs/.emacs.d/elpa/ac-php-core-20240115.530/phpctags/bootstrap.php on line 290
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in phar:///home/flaviovs/.emacs.d/elpa/ac-php-core-20240115.530/phpctags/bootstrap.php on line 290
PHP Deprecated:  Return type of ReadableRecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/flaviovs/.emacs.d/elpa/ac-php-core-20240115.530/phpctags/PHPCtags.class.php on line 780
```

This prevents the script to complete which in turn cause lots of cryptic error messages on emacs side.

Tried the following approaches, none did work:
- Added `error_reporting(E_ALL & ~(E_NOTICE | E_DEPRECATED))` to the top of phpctags -- failed due to phar hash mismatch
- Tried to add the `-d error_reporting=0 -d display_errors=0` to `ac-php-php-executable` -- failed because command is not interpreted by the shell

I've worked around this by creating a php wrapper script that calls the actual php with the correct _-d_ flags but ideally the script should work out-of-box, or a new emacs variable (`ac-php-php-extra-args`?) could be used to provide custom parameter to PHP.

**Comment by xcwen** [comment]
retest

**Comment by flaviovs** [comment]
Working perfectly now, many thanks!
