### ISSUE TITLE
Use XDG_CACHE_HOME instead of ~/.ac-php

### ISSUE THREAD

**Issue by marcinant** [xcwen/ac-php#19]
As in topic. Is this possible to move tags dir to cache?

**Comment by xcwen** [comment]
(defvar ac-php-tags-path (concat (getenv "HOME") "/.ac-php")
  "PATH for ctags to be saved, default value is \"~/.ac-php\" as base for

**Comment by marcinant** [comment]
So, how is it customizable?

setq ac-php-tags-path doesn't work.

**Comment by xcwen** [comment]
(setq ac-php-tags-path "/tmp/ac-php" )
