### ISSUE TITLE
How it's better than company-gtags?

### ISSUE THREAD

**Issue by marcinant** [xcwen/ac-php#21]
Could you please explain how this mode is better than ggtags-mode + company-gtags backend + GNU global?

I just installed GNU Global and personally I don't see any difference in completion, while GNU Global is much faster than this backend.

**Comment by xcwen** [comment]
[xx](https://raw.githubusercontent.com/xcwen/ac-php/master/images/ac-php.gif)

**Comment by xcwen** [comment]
[work pic](https://raw.githubusercontent.com/xcwen/ac-php/master/images/ac-php.gif)
