### ISSUE TITLE
ac-php cant run in windows?

### ISSUE THREAD

**Issue by zerodeng1988** [xcwen/ac-php#22]
When i open the php project,the error is coming like this :file-error "Creating directory" "invalid argument" "d:/Program Files/emacs-24.5-bin-i686-mingw32/.ac-php/tagsd:-zero-develop-www-baoming.It seems ac-php cant run well in windows?But if i open a simple php file ,ac-php run well.

**Comment by xcwen** [comment]
是的, 对了,emacs 在 window 下好用吗?!

**Comment by zerodeng1988** [comment]
@xcwen 一般般，好多配置在window下面都是需要自己去探索的......顺便问问，你身边有别的window下面用emacs开发PHP的人吗?他们PHP使用的是什么插件包?

**Comment by xcwen** [comment]
我们都是的ubuntu 下开发:>

**Comment by xcwen** [comment]
看看是不是不报那个错误.
https://github.com/xcwen/ac-php/commit/8e76342405be596bd2e5a32b595c137173b29674

**Comment by zerodeng1988** [comment]
Error running timer `ac-update-greedy': (file-error "Creating directory" "invalid argument" "d:/Program Files/emacs-24.5-bin-i686-mingw32/.ac-php/tagsd:-zero-develop-www-baoming") [4 times]

Error running timer `ac-show-menu': (file-error "Creating directory" "invalid argument" "d:/Program Files/emacs-24.5-bin-i686-mingw32/.ac-php/tagsd:-zero-develop-www-baoming")
Saving file d:/zero/develop/www/baoming/Activity/Lib/Action/Home/ActivityAction.class.php...
Wrote c:/Users/zerodeng/AppData/Local/Temp/.!drive_d!zero!develop!www!baoming!Activity!Lib!Action!Home!ActivityAction.class.php.~undo-tree~
Wrote d:/zero/develop/www/baoming/Activity/Lib/Action/Home/ActivityAction.class.php

Error running timer `ac-update-greedy': (file-error "Creating directory" "invalid argument" "d:/Program Files/emacs-24.5-bin-i686-mingw32/.ac-php/tagsd:-zero-develop-www-baoming") [3 times]

我更新了ac-php任然报这个错误。你修改的正则后应该是tagsd--zero-develop-www-baoming这样？

**Comment by wjain** [comment]
@zerodeng1988 
ac-php-core.el 文件中的 (defun ac-php--get-tags-save-dir(project-root-dir  )  方法做如下修改：

(replace-regexp-in-string "[/ ]" "-"     ===》  
(replace-regexp-in-string "[/ :]" "-"

":" 不能出现在文件名中。

**Comment by xcwen** [comment]
@wjain  thanks

**Comment by wjain** [comment]
When ac-php-remake-tags-all next error:
eval: Spawning child process: invalid argument

"start-process" can't recognize phpctags on windows.

So, I rename phpctags to phpctags0 and create phpctags.bat in the same path.

```
@echo off
set phpctags=%~dp0\phpctags0
php "%phpctags%" %1
```

**Comment by xcwen** [comment]
@wjain  retest. you can fork it ,  and commit
