### ISSUE TITLE
How can you change the default autocomplete key to something else and preserve tab behavior?

### ISSUE THREAD

**Issue by srcspider** [xcwen/ac-php#23]
The php-mode seems to disable the ability to indent with tabs. I've tried to figure it out but even looking at your code I'm a bit stuck. How can the binding for tab that's set by ac-php be overwritten?

For example make M-` autocomplete and TAB key insert actual tab characters.

**Comment by xcwen** [comment]
reset tab key binding .
(global-set-key (kbd "tab")  .... )

**Comment by srcspider** [comment]
I've tried a few variations of that. It doesn't work.

The following for example,

``` emacs
(defun insert-tab-char ()
  (interactive)
  (insert "\t"))

(define-key global-map "`" 'insert-tab-char)
(global-set-key (kbd "TAB") 'insert-tab-char)
```

Will insert tabs with the ` key but the tab key is still completely non-functional.

**Comment by xcwen** [comment]
M-x: describe-key
find what tab bind .
then find  where is bind code .
change it .

**Comment by srcspider** [comment]
It says it's bound to the indentation function, but only seems to autocomplete. Unfortunately I don't understand lisp that well to get how it's scoping works when it comes to what logic it uses to access functions.

Closing since I don't know what to think of this anymore. I'll just assume I did something strange with my setup.
