### ISSUE TITLE
Request for feature: Property Hinting

### ISSUE THREAD

**Issue by webdevelopers-eu** [xcwen/ac-php#24]
Would it be possible to support dynamic property object hinting without static property declarations?

``` php
$api=new API;
$api->common=new Common;
$api->common->[AUTOCOMPLETE?]
```

or

``` php
$api=new API;
/** @var $api->common Common */
$api->common->[AUTOCOMPLETE?]
```

Thanks. Your project is a great help to me.

PS: Our API is using __get() to dynamically load services based on XML specification. We can autogenerate helper files from our XML definitions to hint what property is what... That would be a great feature as all APIs are dynamically loaded that way.

**Comment by xcwen** [comment]
/**
- @property  \Test\Testa  $v1
- @method  int add($a,$b) 
- @use  \Test\TestC
  */
  class Testb  extends Ta { 
  ...
  }

**Comment by webdevelopers-eu** [comment]
Great! You rock!

I have generated shadow PHP file from XML specifications

``` php
/**
@property Service1 $service1
@property Service2 $service2
...
*/
class API {}
```

And it got correctly merged and properties are available to autocompletion now.

Thanks!
