### ISSUE TITLE
Unable to install company-php through melpa?

### ISSUE THREAD

**Issue by etu** [xcwen/ac-php#26]
Since [this](https://github.com/melpa/melpa/pull/3883) happened, I've been unable to fetch company-php or ac-php-company in an easy manner via melpa.

Is there a solution for this on it's way? Because it completely broke my config and workflow.

**Comment by xcwen** [comment]
sorry , you can copy  company-php.el  to you config . and install ac-php

**Comment by etu** [comment]
I'm sorry, but are you serious?

Will there be a real solution any time soon? Like a separate package to install?

**Comment by ghost** [comment]
I hit this problem too. Will there be a solution soon?

**Comment by xcwen** [comment]
``` elisp
(add-hook 'php-mode-hook
          '(lambda ()
             (require 'company-php-in-ac)
             (company-mode t)
             (add-to-list 'company-backends 'company-ac-php-backend )))
```

company-php => company-php-in-ac

**Comment by etu** [comment]
But will it be changed in melpa as well so we can get the file `company-php-in-ac` in some convinient way? Like a separate package?

**Comment by Dragnucs** [comment]
What are you doing? Each update breaks the package right now.

**Comment by xcwen** [comment]
sorry :<  , i update new now .
[update elpa ](https://github.com/melpa/melpa/pull/4011)

**Comment by etu** [comment]
@xcwen Looks perfect! Thank you :)

Just waiting for melpa to merge and build before I close this issue so I can test it ;)

**Comment by ghost** [comment]
Excited to try this. Thank you.

**Comment by etu** [comment]
Melpa seems to have built `company-php`, `ac-php-core` and `ac-php` just now. Seems to work great :+1:

**Comment by ghost** [comment]
Thanks for working on this. I managed to get it installed and working with spacemacs.

I do notice some strange behaviour. When I select a completion from the list (by pressing tab), an extra ) is added. For example:

``` php
$q = new SplQueue();
$q->pop TAB
```

I would expect it to insert `$q->pop()` after I press TAB but instead I get `$q->pop())`

Anyone else observe this?

**Comment by ghost** [comment]
Seems to be a problem when using ac-php with smartparens-mode. I raised #31

**Comment by lincoln-liu** [comment]
Still can not install from melpa:  Need package `company-1', but only 0.9.0 is available

**Comment by xcwen** [comment]
ok .^_^
