### ISSUE TITLE
No buffer named error

### ISSUE THREAD

**Issue by ivories** [xcwen/ac-php#3]
My project dir : /www/MyProject
When i use 'ac-php-find-symbol-at-point',
I get the error No buffer named /www/MyProject//MyProject/Model/TaskIndex.php

**Comment by xcwen** [comment]
cd .tags&& rm -rf 
retest

**Comment by xcwen** [comment]
M-x ac-php-remake-tags-all
and retest

**Comment by ivories** [comment]
ac-php-20150625.2015 
I remove .tags,
M-x ac-php-remake-tags
test ag,
error ag.

**Comment by xcwen** [comment]
make a test project about it  ,  send to me  xcwenn@qq.com

**Comment by ivories** [comment]
I download the ac-php/phptest,
mkdir .tags
then ac-php-remake-tags
other function is ok,
but the msg: No buffer named /www/phptest//phptest/testb.php is always have,
Is my emacs setting is wrong?or i must update the ac-php ?
I send the emacs setting for you? My system is mac os x

**Comment by xcwen** [comment]
fix

**Comment by ivories** [comment]
test ok, but new error happen.

error msg:
I don't know when this happen..
Wrong type argument: stringp, nil

**Comment by xcwen** [comment]
set it：
(setq debug-on-error t )
and retest.

**Comment by ivories** [comment]
already test it ,but nothing happen..

**Comment by xcwen** [comment]
fix

**Comment by xcwen** [comment]
fix
