### ISSUE TITLE
Smartparens mode and company mode conflict

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#31]
With `smartparens-mode` and `company-mode` enabled using the `company-php` backend; redundant parenthesis are added. It looks like both `company-ac-php-backend` and smartparens are adding a ).

I found [this](https://github.com/xcwen/ac-php/blob/master/company-php.el#L114) line adding the ) in `company-ac-php-backend`. Removing it stops the extra ) being added; but then arguments are not properly added to the completed function.

I'm sure it's a straightforward fix, but I don't know enough about elisp to fix it :(

**Comment by xcwen** [comment]
disable Smartparens
 (insert (concat doc ")") )
re enable Smartparens
?!
