### ISSUE TITLE
Can it be speeded up?

### ISSUE THREAD

**Issue by tworthington** [xcwen/ac-php#35]
When I use this on a Moodle install (1m+ LOC) it can lock up for minutes at a time. Is there any hope of supporting such a large code base? Or, perhaps, is there already something I can do?

https://download.moodle.org

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#configue-php-file-search-for-large-project

**Comment by tworthington** [comment]
Yeah, I know, but it's not obvious what that achieves. Are you saying that I should run ac-php-remake-tags and _then_ edit .ac-php-conf.json to remove the core files?

**Comment by xcwen** [comment]
config it ,you need add.
for laravel example

{
  "use-cscope": false,
  "filter": {
    "php-file-ext-list": [
      "php"
    ],
    "php-path-list": [
        "./app",
        "./database",
        "./vendor/laravel/framework/src/Illuminate"
    ],
    "php-path-list-without-subdir": []
  }
}

**Comment by renatofdds** [comment]
It would be very interesting if you could change ac-php-rebuild-tags (which is usually configured to be hooked in after-save) to work asynchronously (using the async library).

**Comment by xcwen** [comment]
@renatofdds 
async library?! what ?!

**Comment by renatofdds** [comment]
@xcwen [emacs-async](https://github.com/jwiegley/emacs-async) it's a wrapper around start-process.
