### ISSUE TITLE
company-mode support

### ISSUE THREAD

**Issue by kostajh** [xcwen/ac-php#4]
Hi, would it be possible for this project to support company-mode?

**Comment by xcwen** [comment]
i never use   company-mode , and unknown  how to fix it:<
if you known it . fork   and help me ^_^

**Comment by kostajh** [comment]
I would if I had the knowledge how to! :-)

I'll try again to get `ac-php` working... While it worked with the test files mentioned in the README, I couldn't get it working with a large Drupal 7 project.

**Comment by xcwen** [comment]
why , you can move a part of  Drupal 7 project into phptest  ,and test . to find why can't work.

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#lager-php-project-config
maybe help you .

**Comment by kostajh** [comment]
Adding these two links in case someone feels inspired: https://github.com/company-mode/company-mode/wiki/Writing-backends http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend

I tend to think more people would use this package if it supported Company mode, but could be wrong about that!

**Comment by xcwen** [comment]
ok ,i test it .

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#usage-company
 work done !

**Comment by kostajh** [comment]
wow, looking forward to trying it out! I'll post back here after testing.

**Comment by kostajh** [comment]
Thanks @xcwen, I'm still working on getting this set up properly. I'm using Spacemacs so the install set up is a little different than your README instructions. If you're curious to have a look, see https://github.com/syl20bnr/spacemacs/pull/3943

**Comment by xcwen** [comment]
spacemacs  is so beautiful,
i test it ^_^
