### ISSUE TITLE
How to add all sub dir in project root?

### ISSUE THREAD

**Issue by Anan5a** [xcwen/ac-php#40]
I've a php project and there are a lot of sub dir which include codes. Is there any option so I can add only parent dir and all sub dir scanned automatically?

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#configue-php-file-search-for-large-project
may be help for you.

**Comment by Anan5a** [comment]
I installed it from melpa and there's no command named ```ac-php-remake-tags```  :(
http://stackoverflow.com/questions/39950099/ac-php-package-not-working-in-emacs help

**Comment by xcwen** [comment]
re install
