### ISSUE TITLE
配置在最新的 spacemacs develop 分之下报错 

### ISSUE THREAD

**Issue by motecshine** [xcwen/ac-php#45]
会爆void var错误 config.el在第一行

**Comment by xcwen** [comment]
我搞了一下,没成功,你能改改吗^)^

**Comment by wjain** [comment]
我用的 sapcemacs develop 的最新版，ac-php 没遇到你的问题，不知道你说的 void var 错误是在什么情况下出现的？

**Comment by motecshine** [comment]
@xcwen 我也不会

**Comment by motecshine** [comment]
@wjain  我更新下源 重新试试

**Comment by motecshine** [comment]
@wjain  
![image](https://cloud.githubusercontent.com/assets/7615270/22148889/ad8565d6-df4b-11e6-9773-eaefe2f0487e.png)

**Comment by xcwen** [comment]
好了,修复了 ! 
更新一下 phpplus
https://github.com/xcwen/spacemacs-config/tree/master/layers/phpplus

**Comment by motecshine** [comment]
sorry太忙了已经用上了
