### ISSUE TITLE
Not working with company-quickhelp

### ISSUE THREAD

**Issue by kaaresl** [xcwen/ac-php#47]
The company-php front-end causes some trouble with the [company-quickhelp](https://github.com/expez/company-quickhelp) package. See issue expez/company-quickhelp#65 and the explanation about expected parameters.

**Comment by cyrialize** [comment]
I cannot get company-php to work with quickhelp at all. I'm not getting any of the errors that are linked above.

**Comment by xcwen** [comment]
![a](https://user-images.githubusercontent.com/1539162/39896483-d89bcea2-54e0-11e8-9dc3-2fae60bf7761.png)
fixed it, retest .

**Comment by cyrialize** [comment]
It works! Thank you so much. My only nit pick is that I wished it would show the documentation for the function as well - but I imagine that will be coming in the future. Plus, I'm learning emacs lisp so I'll definitely contribute to the project once I know more. Again, thank you so much. This extension makes PHP development on Emacs amazing.
