### ISSUE TITLE
Dereferencing objects

### ISSUE THREAD

**Issue by y-ates** [xcwen/ac-php#53]
It seems like it won't reference objects far enough. Let me explain this by an example:

```
class A{
    private $objectB;

    public function __construct($paramB){
        $this->objectB = $paramB;

        /*
         * ac-php won't autocomplete after $this->objectB
         * so it won't show any functions available of objectB.
         */
        $this->objectB->functionOfB();
    }
}
```

It would be awesome if ac-php could also dereference objects so that the developer gets a list of available functions of that object.

**Comment by xcwen** [comment]
/**
     * @var ObjectB_class_name;
     */
    private   $objectB;

you need define it .

**Comment by y-ates** [comment]
I am dumb. Yes thanks :D.
