### ISSUE TITLE
Use PhpDoc @var syntax for explicit variables

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#54]
Hi, thanks for a great plug-in.

It seems`ac-php` uses the PhpDoc @var syntax `/** @var $value  Testa */` instead of the PhpDoc official `/** @var Testa $value */`. Would be great if it supported PhpDoc official syntax for @var.

[PhpDoc @var](https://phpdoc.org/docs/latest/references/phpdoc/tags/var.html)

**Comment by xcwen** [comment]
ok .

**Comment by xcwen** [comment]
like this?!
```php
class Foo
{
  /**
   * @var string $name        Should contain a description
   * @var string $description Should contain a description
   */
  protected $name, $description;
}
```

**Comment by ghost** [comment]
Yes, exactly, the @var syntax for implicit variable name is correct so don't change that. It's just in the case where variable name is explicitly defined that the type needs to come before the variable name. I think this example is another use case:

```
/** @var MyClass */
$myClass = $factory->getDynamicObject('MyClass');

if (is_a($myClass, 'NewClass')) {
    /** @var NewClass $myClass */
}
```

**Comment by xcwen** [comment]
ok , now is ok .
now  is surpported: 
```php
 /** @var NewClass $myClass */
```
  isn't surpported: 
```php
/** @var MyClass */
$myClass = $factory->getDynamicObject('MyClass');
```

**Comment by ghost** [comment]
Thank you

**Comment by ghost** [comment]
Just out of curiosity, I tested this in the latest PhpStorm:

```
/** @var MyClass */
$myClass = $factory->getDynamicObject('MyClass');
```

And it doesn't seem to support it either. Maybe it's invalid PhpDoc syntax, so don't bother about it.
