### ISSUE TITLE
PHP-Parser croaks on anonymous classes

### ISSUE THREAD

**Issue by tomterl** [xcwen/ac-php#55]
Using anonymous classes leads to parse errors. I saw in the composer.lock file that the PHP-Parser version used is rather old, with 1.x locked in -- the latest release is 3.x.

Is it possible to build the phpctags version shipped with ac-php with a newer PHP-Parser version, or is the composer.lock contents just misleading?

kind regards,
Tom

**Comment by xcwen** [comment]
retest .

**Comment by tomterl** [comment]
Wow, ultrafast reaction time :-) 
 I just dropped in the new phpctags,  works like a charm. Thanks!
