### ISSUE TITLE
Fails to index Magento 2

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#56]
Try running `ac-php` on Magento 2.

**Step to reproduce:**
1. [Get the Magento CE metapackage](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/integrator_install_ce.html) i.e. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`
2. Create file `ac-php-conf.json` in project root i.e.`touch .ac-php-conf.json`
3. Try `ac-php-remake-tags-all` in Emacs in Magento 2 root

**Expected result:** Process finishes without errors
**Actual result:**
```
do remake /Users/christianjohansson/Web/Magento2/Magento 2/
 REBUILD: load file  modify time  start
 REBUILD:  rebuild file start
 REBUILD final start   
 REBUILD:  cache2-file-list ... 
[cache2]BUILD marge files (count=24945 ) start...
[cache2]BUILD marge files end  and then start deal ...
tags-list deal .... 
save to  /Users/christianjohansson/.ac-php/tags-Users-christianjohansson-Web-Magento2-Magento-2//tags-data-cache2.el ...
 REBUILD:  cache1-file-list ... 
[cache1]BUILD marge files (count=10 ) start...
[cache1]BUILD marge files end  and then start deal ...
tags-list deal .... 
 reset inherit-list ...  count=18386 
 add-class-list count=22293 ... 
  reset inherit-list  end  
save to  /Users/christianjohansson/.ac-php/tags-Users-christianjohansson-Web-Magento2-Magento-2//tags-data.el ...
REBUILD END :ERROR 
PHPParser: No code may exist outside of namespace {} on line 27 - /Users/christianjohansson/Web/Magento2/Magento 2/vendor/magento/framework/ObjectManager/Test/Unit/_files/logger_classes.php
Mark set [2 times]
 REBUILD final start   
 REBUILD:  cache2-file-list ... 
[cache2]BUILD marge files (count=24945 ) start...
[cache2]BUILD marge files end  and then start deal ...
tags-list deal .... 
save to  nil ...
error in process sentinel: ac-php-save-data: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
```
It seems like it doesn't support files with multiple namespaces where namespaces are defined using brackets.

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#configue-php-file-search-for-large-project
may be can help you :>

**Comment by ghost** [comment]
This looks like an issue in PHPParser with files using bracketed namespaces and have comments outside of the brackets. I investigated it further and created a issue [there](https://github.com/nikic/PHP-Parser/issues/412)
