### ISSUE TITLE
Reversion

### ISSUE THREAD

**Issue by tworthington** [xcwen/ac-php#57]
Commit 5be2a4a9819f9685a1f6c464afd8bbc042d94575 reintroduces the bug that the cache folder uses a non-canonical name if the source tree has symbolic links in it, leading to (unsynched) duplication of the caches. This was the motivation for my patch which was merged in as commit eae248e0f3a90fc797c370c2021f241c4c24f044 in January which 5be2a4 undoes.

The main use case I'm encountering is that /www/ is often a link to /var/www/, so ac-php is creating caches for both those trees depending on exactly which one I followed while opening a given file.

**Comment by xcwen** [comment]
sorry :>
