### ISSUE TITLE
Include external library

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#60]
Hi!

Thanks for a great plugin, I use it every day.

I have some projects that depend on libraries that are global. Like if I have a project in `~/Web/Site1/` it may depend on a library in `~/Web/library/`. Is it possible to include paths outside of document root in the `ac-php-conf.json`? If not, can you add that feature? It's not an option for me to have the configuration at `~/Web/ac-php-conf.json` because I have about 100 projects and I don't want to index them all together.

Regards

**Comment by aitte2** [comment]
Have you tried including these paths in the json conf to see if any work:

../libraries

/../libraries

~/Web/libraries

/home/foo/Web/libraries

**Comment by ghost** [comment]
Ok testing, Results

* using `~/Web/libraries`: CONFIG FILTER WARRING : ..most in project-root-dir.. REBUILD SUCCESS but doesn't work
* using `../libraries` same result as above
* using `/../libraries/` same result as above
* using `/Users/cjohansson/Web/libraries` same result as bove

So neither method worked

**Comment by xcwen** [comment]
```json
{
  "use-cscope": null,
  "tag-dir": null,
  "filter": {
    "can-use-external-dir": true,
    "php-file-ext-list": [
      "php"
    ],
    "php-path-list": [
        ".",
        "~/tt/app/Enums"
    ],
    "php-path-list-without-subdir": []
  }
}
```
use "can-use-external-dir": true   for it .

if jump to external library will not work with .ac-php-conf.json :<

**Comment by ghost** [comment]
Tested it now. It works, thanks for such quick response! 👍
