### ISSUE TITLE
AC-PHP doesn't understand PSR-2 Arguments Style 2

### ISSUE THREAD

**Issue by aitte2** [xcwen/ac-php#61]
Hi, just noticed something.

Look at PSR-2 function styles:

http://www.php-fig.org/psr/psr-2/#44-method-arguments

AC-PHP understands this style:

```php
<?php
namespace Vendor\Package;

class ClassName
{
    public function foo($arg1, &$arg2, $arg3 = [])
    {
        // method body
    }
}
```

Does not understand this style:

```php
<?php
namespace Vendor\Package;

class ClassName
{
    public function aVeryLongMethodName(
        ClassTypeHint $arg1,
        &$arg2,
        array $arg3 = []
    ) {
        // method body
    }
}
```

If PSR-2 style 2 is tried, the `ac-php-show-tip` will only show `aVeryLongMethodName(`, it will not show function arguments.

It's a minor problem but it's a problem :O

**Comment by xcwen** [comment]
delay

**Comment by xcwen** [comment]
fixed

**Comment by aitte2** [comment]
@xcwen Hi, wow big work, thanks a lot! I see your new `get_args` in phpctags... Looks great and correct!

I cannot test successfully though. Somehow there is a problem in `company-ac-php-backend`?

```
Company: An error occurred in auto-begin
Company: backend company-ac-php-backend error "Wrong type argument: hash-table-p, nil" with args (candidates array)
Company: An error occurred in auto-begin
Company: backend company-ac-php-backend error "Wrong type argument: hash-table-p, nil" with args (candidates array_)
eldoc error: (wrong-type-argument hash-table-p nil)
Company: An error occurred in auto-begin
Company: backend company-ac-php-backend error "Wrong type argument: hash-table-p, nil" with args (candidates array_)
eldoc error: (wrong-type-argument hash-table-p nil)
```

Here is the test project I am trying:

[test.zip](https://github.com/xcwen/ac-php/files/1464978/test.zip)

I open that file, I run `ac-php-remake-tags-all`, then I type `$this->` and I just get the error above.

Is my zip file project working for you?

I have latest ac-php and latest company:

https://github.com/xcwen/ac-php/commit/766b96e4284944a00ff648add5c7cd65b25e776e

**Comment by aitte2** [comment]
Also noticed:

`phpctags\PHPCtags.class.php`: The function `gen_args_default_str` has no code to support `[]` (empty array).

So it turns:

```php
    public function aVeryLongMethodName(
        ClassTypeHint $arg1,
        &$arg2,
        array $arg3 = []
    ) {
        // method body
    }
```

to:

`["m","aVeryLongMethodName","$arg1, $arg2, $arg3=","0:12",null,"\\Vendor\\Package\\ClassName","public"]`

Notice the problem? `"$arg1, $arg2, $arg3="`

It's probably meant to be `"$arg1, $arg2, $arg3=[]"`?

**Comment by aitte2** [comment]
I like the new json format a lot btw :)

**Comment by xcwen** [comment]
retest .

**Comment by aitte2** [comment]
@xcwen 我爱你!

Autocomplete: PERFECT.
Array `= []`: PERFECT.
String `= ''`: PERFECT.
Function with many lines of arguments: PERFECT.

YOU ARE GREAT!!!! :D

![perfect](https://user-images.githubusercontent.com/18485256/32735712-c9ea82a4-c895-11e7-849f-d9215002eebd.png)

![perfect2](https://user-images.githubusercontent.com/18485256/32735808-078d54c4-c896-11e7-82ff-32f0f9ea7d7e.png)

**Comment by ghost** [comment]
<3 :-)
