### ISSUE TITLE
Bug: Incorrect handling of sub-namespaces and relative namespaces

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#62]
Hi @xcwen, I've found a bug. :-O

If a class has the same name as a sub-namespace (which is valid to do), then AC-PHP gets confused and cannot autocomplete.

I have attached a tiny project to demonstrate the AC-PHP parser bug:

[testproject.zip](https://github.com/xcwen/ac-php/files/1384346/testproject.zip)

The problem is that AC-PHP's parser doesn't understand when a namespace has the same name as a class too.

I think (and hope) the bugfix is easy, by just making AC-PHP look for `\` backslash, to automatically understand that "`<someclass>\somethingelse`" means that `<someclass>` in that case is NOT a class reference but is a NAMESPACE reference.

**Comment by xcwen** [comment]
delay..

**Comment by ghost** [comment]
I understand. Hope you are feeling ok. :)

**Comment by ghost** [comment]
I think the bug is maybe a different one than what I first thought...

Here's another example:

- **src/test.php**:
```php
<?php

namespace foo;

class test
{
    /**
     * @return model\item
     */
    function getItem() {
    }
}

$x = new test();
// Try this: $x->getItem()-> // AC-PHP says: No find model/item...
```

- **src/model/item.php**
```php
<?php

namespace foo\model;

class item
{
    /**
     * @return string
     */
    function getName() {
        return 'x';
    }
}
```

So I think I know what the bug is... AC-PHP sees "model\item" and thinks it's `\model\item`). It should understand `namespace foo;` of the current file and always interpret the relative class path as relative to the current namespace, such as `\foo\model\item` in this situation.

Only class paths that start with backslash (like `@return \foo\model\item`) should be interpreted globally. Everything else is always relative to the current file's namespace!

Also: `use X;` and `use X as Y;` need to be understood properly, so that `use Guzzle\Guzzle as G;` and `@return G` are understood properly for example...

But one thing at a time... the most important bug fix is the lack of relative namespace support. Because most namespaces in big projects are written relatively instead of big, long, full paths. ;-)

I think fix would be something like:
```
if name[0] === '\':
   fullpath = name
else:
   fullpath = currentFileNamespace + '\' + name;
```

AC-PHP is close to perfect... this is the only bug I can't live with... :-) Great work so far!

💋

**Comment by xcwen** [comment]
retest

**Comment by ghost** [comment]
@xcwen Oh my god this is perfect. Thank you so much. I just tested EVERY variable in the test-project zip I attached above. And the text test-project I posted above too.

I tested every variable, every kind of access, and ALL of them point to the correct classes now.

- `use` statements are supported.
- Relative `Some\Class` works.
- Relative `Class` works.
- Full path `\Foo\Some\Class` works.

Now it's perfect! :-D Holy shit. Thank you!

What was the fix? I don't understand it:
https://github.com/xcwen/ac-php/commit/53f745d1ceb3a1785876c626160d6ae283e07074

It looks like the old code did: "If variable type contains `\` anywhere, use classname, else use namespace + classname". So the if the old code saw a `Some\Class`, it thought it was `\Some\Class`.

Now it instead _always_ does "use namespace + classname". I don't understand how this code is able to work in the `\Full\Path` style. It looks like it would create a `\Foo\\Full\Path` in that case?

**Comment by ghost** [comment]
I think maybe the correct fix would be this instead:

```emacs-lisp
(if (= 0 (s-index-of "\\" tmp-class ))
     tmp-class
  else... the other code
```

**Comment by ghost** [comment]
That code would check if the 1st character is `\` (backslash) and if so uses the tmp-class name as it is. Else, it does the code that joins the namespace + tmp-class name.

I think you should update the commits to take back the code you commented out here:
https://github.com/xcwen/ac-php/commit/53f745d1ceb3a1785876c626160d6ae283e07074

And just change the if to what I posted above. It returns true if the 1st character is `\\`. That way, full paths like `\Foo\Bar` will not run the namespace+classname joiner. Just as you originally intended. The only problem with the old check was that it reacted to `\` ANYWHERE in the `tmp-class` string. With this small change I've listed it reacts only to `\` at the start.

**Comment by xcwen** [comment]
ok :>

**Comment by ghost** [comment]
xD

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php/commit/c7881ebfbba478f6b83c586d14e85716c8681d28

**Comment by ghost** [comment]
@xcwen Thanks, that looks better! I will download it and try all cases again :)

**Comment by ghost** [comment]
@xcwen This is weird... I have been comparing with that line on and off, and whenever I use my proposed `= 0` fix, I get this error when I try to access `$this->request` (the variable defined as `@var Request`.

![x](https://user-images.githubusercontent.com/22373193/31862838-0a8231de-b745-11e7-8047-7188f70ac7a9.png)

But other relative variables like `@var Request\DeepRequest` work and also `@var \Foo\Request\DeepRequest`... Wtf. Any idea why just `@var Request` fails now?

Even `@var Deep` (from `use Foo\Request\DeepRequest as Deep;`) works!

ONLY `@var Request` fails...

**Comment by ghost** [comment]
You can download the test-project from my 1st post here and try it... It's very weird.

After the `= 0` fix, ALL variables EXCEPT `$this->request` works... Wtf.

**Comment by ghost** [comment]
It looks like my fix was correct but that something else is confusing it... this is weird.

**Comment by ghost** [comment]
@I am pretty sure that `@var Request` will take the 2nd code-path (go concat namespace + `\` + classname).

And ALL other examples work:

```php
namespace Test;
use Test\Request\DeepRequest as Deep;
class Foo {
    /** @var Request */
    public $requestfails;

    /** @var \Test\Request */
    public $requestworks;

    /** @var Request\DeepRequest */
    public $deeprequestrelativeworks;

    /** @var \Test\Request\DeepRequest() */
    public $deeprequestworks;

    /** @var Deep */
    public $deeprequestworks2;

}
```

The ONLY one that fails is `$this->requestfails`... But it shouldn't fail. It [should concat](https://github.com/xcwen/ac-php/commit/c7881ebfbba478f6b83c586d14e85716c8681d28) as "Test\Request". This is so weird!

**Comment by ghost** [comment]
I am trying to solve this so I have put some debug messages in the ac-php-core.el algorithm to try to find what is going wrong...

**Comment by ghost** [comment]
Okay I have found something interesting...

`@var \Test\Request` even in this example, the `tmp-class` variable is just `Test\Request`. So there is never any leading `\` in tmp-class, so my proposed code change was pointless...

We can delete the whole:
```emacs-lisp
  (if  (= 0 (s-index-of "\\" tmp-class ) )
   tmp-class
```

Because that code will never run. No types have a leading `\` in them inside of ac-php's handling.

Hmm... I still don't understand why adding that back made `@var Request` fail though... Because my code above literally only goes to the "Else" because it's NEVER true. So how does that make it fail... weird.

**Comment by ghost** [comment]
OHH I UNDERSTAND now... I found the bug.

`(s-index-of "\\" tmp-class)` returns nil when no match.

`@var Request` is a class with no `\` in it (Unlike `@var Deep` which is a `Foo\Request\DeepRequest` alias via `use-statement`).

So that is why `@var Request` fails. It finds no match with s-index-of... so it returns `nil`.

`(= 0 nil)` is an invalid comparison, so emacs lisp says `wrong-type-argument number-or-marker-p nil`

**Comment by ghost** [comment]
So there are two problems here:

1. We should totally delete the `(if  (= 0 (s-index-of "\\" tmp-class ) )` comparison. That code will never run (not in the past and not now).

2. The original purpose of that code was to look for `\Foo\Bar` (absolute class paths) and using them as-is... But that's not going to work, since ac-php treats `\Foo\Bar` as `Foo\Bar` internally.

So... forget it. Let's just delete the `s-index-of` as you did in the original fix.

And also: I noticed that the rest of the code always runs, with the following behavior:

`@var \Test\Request`
```
cur-namespace = Test
tmp-class = Test\Request
check-classname = Test\Test\Request
```

Then it runs this code (inside the `progn` (which returns the value of the latest statement):

```emacs-lisp
(if (assoc-string check-classname class-list t )
     check-classname tmp-class )
```

I looked at `assoc-string`. The docs say: It returns the value `check-classname` if it exists in `class-list`, or nil if no matches exist.

And your code says: If non-nil: Use `check-classname` otherwise use `tmp-class`

So... okay, do you understand? Your current code is pretty okay. It's not perfect, but it's okay enough... It has some bugs though.

Here's what happens currently:

- `@var \Test\Request`
- Try resolving as `Test\Test\Request`, if that exists in the list of classes, use `Test\Test\Request`.
- Else, use `Test\Request`

- `@var Request`
- Try resolving as `Test\Request`, if that exists in the list of classes, use `Test\Request`.
- Else, use `Request`.

This comment is already too long so I will explain what to do in the next comment.

**Comment by ghost** [comment]
Here's what to do:

1. Remove the `if s-index-of` completely. The line we added is wrong and crashes... as I said above. :\
2. Consider if you want to fix the parser, so that `@var \Test\Request` is handled internally as `\Test\Request` and `@var Request` is handled internally as `Request`. Because currently there's a bug where absolute namespace paths will always be resolved via testing `Namespace + ClassName` first. If such a path is found, then it will be used even if it's wrong. Absolute paths should always be used if `@var \` format is used. With no testing of sub-namespaces... Otherwise wrong classes can be found.

This is the bug:

```php
namespace Test;

class Foo {
    /** @var \Other */
    public $other;
}
```

Even before this ticket, AC-PHP would try that as:

`Test\Other`, and if it finds `Test\Other`, it uses `Test\Other`. Even though that should ALWAYS be a global path (`Other`).

Because AC-PHP doesn't keep the `\` so it doesn't know that the path is supposed to be global.

But that is a separate, rarer bug...

The most important thing right now, is to totally remove the `s-index-of` check, since the current one we re-added is broken :P

**Comment by xcwen** [comment]
fix 1
the second need sometime to check code ..:<

**Comment by ghost** [comment]
@xcwen Ok, https://github.com/xcwen/ac-php/commit/317ad1d023db6b2fe67444a2c075e656c35f5094 that is a nice fix!

And that code is correct for the future (if you find the time to fix the `@var \Other` bug someday, so that it's keeping that as `\Other` internally).

I think for 2:

- You're already storing correct values in tags `.el` files! I can see stuff like: `("class"."Test\\Foo") "public"  "\\Test\\Request" )` and `("class"."Test\\Foo") "public"  "Request\\DeepRequest" )`. So you're already storing `\Full\Path` vs `Relative\Path`. :)
- Now it just needs some different `ac-php-core` algorithm: Keep the `\` at the start while processing (resolving) the class name. So that we know what paths are full paths vs relative paths!
- If `s-index-of "\\"` (such as `\Test\Request`) then: Use substring from character 1: `Test\Request`. That is the class name!
- Else (such as `Stuff`): Use `concat namespace "\\" classname` (`Foo\Stuff`). That is the class name! That's all! No need to look in `class-list` anymore. Because the correct PHP behavior is to always add the namespace to all relative paths.

It also needs code changes everywhere that expected "cleaned" names without `\` at the start...

I actually tried to look for the code that is removing `\` at the start but couldn't find it, so I gave up. Good luck with it. :O

**Comment by xcwen** [comment]
rewite ac-php , maybe fixed it :>

**Comment by ghost** [comment]
@xcwen This is looking incredible. What a big rewrite. Amazing! If you have a PayPal I would like to donate $5 as thanks (I am not rich hehe). :)

The new JSON data is beautiful. The new autocomplete of complex arguments is great. You have really done an incredible job here.

I noticed two small bugs:

# 1st

First, the way it handles "Use" statements is incorrect.

```php
// This is a "use-statement", class path is always full (\\Global). Never relative.
use Test\Request\DeepRequest as Deep;

class Foo
{
    /** @var Deep */
    public $deeprequestworks2;
}
```

```json
[
    "p",
    "deeprequestworks2",
    null,
    "2:25",
    "Test\\Request\\DeepRequest", <-- Uh oh. Relative! SHOULD be "\\Test\\Request\\DeepRequest"
    "\\Test\\Foo",
    "public"
]
```

How to fix: If `use X` does not start with `\` (`use \X`), add it. But don't just add it every time, because some people write `use \X` in their code (it's not correct to do that, but some people do it anyway).

# 2nd

And the second problem. Is that this code works:

```json
[
    "p",
    "deeprequestworks2",
    null,
    "2:25",
    "Test\\Request\\DeepRequest",
    "\\Test\\Foo",
    "public"
]
```

In this case, I type `$this->deeprequestworks2->` and it actually finds `\\Test\\Request\\DeepRequest` class.

In reality it should do this:

`"\\Test\\Foo"` (minus class name = `"\\Test"`) + `"Test\\Request\\DeepRequest"` = `\\Test\\Test\\Request\\DeepRequest` and should say `Class not found: \\Test\\Test\\Request\\DeepRequest`.

Because what this JSON above says, is:

This is a class named `\\Test\Foo`. It is in `\\Test` namespace. It has a property "deeprequestworks2" with a relative class path `Test\\Request\\DeepRequest`. So the correct final path is: `\\Test\\Test\\Request\\DeepRequest`.

So in the code that searches for a class, I guess you still have the old code that first searches for `\\Test\\Test\\Request\\DeepRequest` and then searches for `\\Test\\Request\\DeepRequest`. That's the wrong and dangerous search.

How to fix: Just remove that code, since it's incorrect and can lead to finding wrong classes! The only thing you should search for is `\\Global\\Path` if a property has a `\\` prefix. Or `\\Namespace\\Relative\\Path` if a property has no `\\` prefix.

Together with this fix it also needs fixed `phpctags` to make sure that phpctags generates proper `\\` prefix to "Use"-statements (as I posted in 1st point above). :-)

Well that's two small issues. ;-) Everything else is super impressive! Please let me know if you have a PayPal.

You can use this https://github.com/xcwen/ac-php/files/1384346/testproject.zip test project as usual, to try the fixes on it.

**Comment by ghost** [comment]
About 2, I think its problem is somewhere in this code in ac-php-core.el:

```emacs-lisp
            (let ( member-info)
              (setq member-info (ac-php-get-class-member-info class-map inherit-map cur-class  item ))
              (setq cur-class (if  member-info
                                  (let (tmp-class cur-namespace check-classname member-local-class-name backslash-pos)
                                    (setq tmp-class (aref member-info 4 ) )
                                    (ac-php--debug "tmp-class %s member-info:%S" tmp-class member-info )
                                    (when (stringp tmp-class )
                                      (setq  backslash-pos (s-index-of "\\" tmp-class ) )
                                      (if  ( and (numberp backslash-pos ) (= 0  backslash-pos)  )
                                          tmp-class
                                        (progn
                                          (setq member-local-class-name (aref member-info 5) )
                                          (setq cur-namespace (ac-php--get-namespace-from-classname member-local-class-name ))
                                          (setq check-classname (concat cur-namespace "\\" tmp-class  ) )
                                          (if (gethash check-classname class-map  )
                                              check-classname tmp-class )))))
                                ""))

              ))
```

It needs to strictly match only: `\\Global\\Path` or `\\Namespace\\Relative\\Path`. Never `\\Relative\\Path` (_that's_ the bug).

**Comment by xcwen** [comment]
first check  global path
next check cur namespace path

**Comment by ghost** [comment]
Hi @xcwen. Not fixed. It's even more wrong now. A class like "@use Foo" would try "\Foo" (global) even though it may be intended to match "\Test\Foo". This means it can find the wrong class and give buggy results. :-(

There are 2 problems, as I said above.

I have fixed Problem 1 now (the problem in phpctags). Here is a patch for you. Just use the whole `PHPCtags.class.php` file here:

# [PHPCtags.class.zip](https://github.com/xcwen/ac-php/files/1471033/PHPCtags.class.zip) (Click this!)


Before my fix (wrong path):

```php
// This is a "use-statement", class path is always full (\\Global). Never relative.
use Test\Request\DeepRequest as Deep;

class Foo
{
    /** @var Deep */
    public $deeprequestworks2;
}
```

```json
            [
                "p",
                "deeprequestworks2",
                null,
                "2:25",
                "Test\\Request\\DeepRequest", <-- wrong!
                "\\Test\\Foo",
                "public"
            ]
```

After my fix:

```json
            [
                "p",
                "deeprequestworks2",
                null,
                "2:25",
                "\\Test\\Request\\DeepRequest", <-- right! :)
                "\\Test\\Foo",
                "public"
            ]
```

About problem 2: I will talk about this in separate message.

**Comment by ghost** [comment]
Problem 2: The correct fix is to restore the old code, and change these things:

1. Somehow KEEP the first backslash in `"\\Test\\Request\\DeepRequest"` inside of ac-php-core's code/logic. It tells ac-php that the path is global (not relative). If you NEED to remove it, at least keep some variable/something like `cur-classpath-is-global` to be sure the "This is a global path!" info is not lost.
2. If path is global (STARTS with `\\` (backslash)), use GLOBAL path ONLY.
3. Else use RELATIVE path ONLY.

Here's an example:

```php
namespace Test;
class Foo
{
    /** @var Relative */
    public $relative;
    /** @var \Absolutelyglobal */
    public $absolute;
}
```

Here's the answer (how to resolve the paths 100% the same way as PHP does it):

### `Relative`:

- `\Relative` = **WRONG**
- `\Test\Relative` = **right**

### `\\Absolutelyglobal`:

- `\Absolutelyglobal` = **right**
- `\Test\Absolutelyglobal` = **WRONG**

---

So we cannot "just search global first, then search relative" etc...

We must, in `ac-php-core.el`, KEEP the `\\` at the START of absolute paths, or at least add a new variable to help it remember that a certain path is global.

Then in the [class-finder](https://github.com/xcwen/ac-php/issues/62#issuecomment-343980543) (click), it must do: If starts with `\\` use GLOBAL ONLY, if not starts with `\\` use RELATIVE ONLY.

You see? ;-)

If we don't do this, stuff like `class Foo {} namespace Bar { class Foo {} class Z { /** @var Foo */ public $foo; } }` would match the wrong class (that example would wrongly pick global Foo instead of its own Foo!).

**Comment by xcwen** [comment]
i don't  think so  about  Problem 1  is a bug. 
for Problem 2: 
```elisp
                                      (if   (ac-php--check-global-name tmp-class )
                                          ;;  like  \test\ss
                                          tmp-class
                                        (progn;; tmp-class like   test\ss
                                              ;; check as  \cur-namespace\test\ss
                                              (setq member-local-class-name (aref member-info 5) )
                                              (setq cur-namespace (ac-php--get-namespace-from-classname member-local-class-name ))
                                              (setq check-classname (concat cur-namespace "\\" tmp-class  ) )
                                              (ac-php--debug " 2 check-classname %s " check-classname )
                                              (if (gethash check-classname class-map  )
                                                  check-classname
                                                (progn
                                                ;; check as global, like: \test\ss
                                                (setq check-classname (concat "\\" tmp-class  ) )
                                                (ac-php--debug "check-classname %s " check-classname )
                                                (if (gethash check-classname class-map  )
                                                    check-classname
                                                  tmp-class
                                                )
                                              ))
                                              ))
```
is ok ?!

**Comment by ghost** [comment]
@xcwen It seems there's a big language barrier.

Problem 1 is a very serious bug. As I explain here:

```php
// This is a "use-statement", class path is always full (\\Global). Never relative.
use Test\Request\DeepRequest as Deep;
```

The old code (before my fix) writes use-statements as Relative paths into `tags.json`. Which makes it impossible to know that the path is global.

They must be written as Global paths into `tags.json`. My patch fixes that:

https://github.com/xcwen/ac-php/issues/62#issuecomment-344267185

Please install it. ;)

**Comment by ghost** [comment]
About problem 2: It can only be solved after problem 1 is fixed via my code.

After problem 1 is fixed, `tags.json` will always have correct paths (global for global, relative for relative).

To fix problem 2, you need correct paths. That is why I did the patch of phpctags.

So first merge/fix problem 1.

**Comment by ghost** [comment]
Then, to fix problem 2: We cannot GUESS about class paths. We must store the info about whether a path is global or relative. We cannot guess. We cannot randomly search for it (as your code has done so far in every version).

We must stop guessing. There's no way to safely find a class with a guess. We must search GLOBAL for GLOBAL vars, and RELATIVE for RELATIVE vars. Never mixing! It is explained here: https://github.com/xcwen/ac-php/issues/62#issuecomment-344269097

There are two solutions to do correct search (global for global, relative for relative):

1. `ac-php-core` must read tags.json without removing the first `\` from properties. The `\` tells us that the path is global. If a path starts with `\` we search globally. If it does not start with `\` we search locally.

2. Alternative solution: Make `phpctags` convert all relative paths to global paths and make it write GLOBAL PATHS FOR EVERYTHING to tags.json. If you do that, then ac-php-core doesn't need to do ANY special scanning. Every class will be a full global path. Then it should just search for global path. Simple.

Both solutions require that you understand the problem. Is there a language barrier? I don't speak Chinese :( Please carefully read the posts I linked above. I hope it makes the problem clear... :(

**Comment by xcwen** [comment]
give me test project code :>

**Comment by xcwen** [comment]
i know what's i'm wrong :>

**Comment by xcwen** [comment]
```php
namespace test\subtest;
class TestA {
    public function Boo(){
        echo "Boo\n";
    }
}


namespace test;
require("./sub.php");
use subtest\testA as T;
class Main extends T {
}
$m=new Main ();
$m->Boo();
```
i got:
PHP Fatal error:  Class 'subtest\testA' not found in /home/jim/test_project/a.php on line 5

:>
so ,you are right thanks :>

**Comment by xcwen** [comment]
fix  Problem 1
and maybe fix  Problem 2 :>

**Comment by ghost** [comment]
Hi @xcwen I've been very sick and tired, sorry for my late reply.

I've now downloaded the latest code and investigated. :-)

You succeeded!

- You have added my `use`-statement path fix to PHPCTags generator, which ensures Use-statements are always treated as global paths (which is the only kinda path they can be). :-) Awesome.
- You have done the perfect fix I suggested earlier: To internally keep the `\` at start of class names (in the `tmp-class` variable) so that we can look for `\` at its start to know the difference between global and relative paths.
- And now you treat `\Path` as global and `Path` as relative. Fantastic!

I wrote a new, tiny test project to test all of this:

[testGlobalRelative.zip](https://github.com/xcwen/ac-php/files/1521091/testGlobalRelative.zip)

I found a small bug and fixed it, so that AC-PHP looks up class names the exact same way as PHP looks up class names. Please merge it:

https://github.com/xcwen/ac-php/pull/63

The test project behaves perfectly _after_ that fix is merged:

Main.php:
- Relative path finds `\Other`
- Global path finds `\Other`

SubConfuse/Confuse.php:
- Relative path finds NOTHING (perfect!). Before my fix (#63), that path went to `\Other` which is wrong!
- Global path finds `\Other`

SubReal/Real.php
- Relative path finds `\SubReal\Other`
- Global path finds `\Other`

Wow... :-)

Merge my pull request, then we can close this ticket finally.

The day has come when AC-PHP is perfect at finding classes.

Thanks a lot for your hard work, we've solved it in the end! ❤️

**Comment by ghost** [comment]
Thanks for merging. Fantastic. We can finally put this work and discussion behind us. ;-)

Every bug from this ticket is now solved!

AC-PHP is really perfect now! Woooooo! `^_^`

**Comment by xcwen** [comment]
:>

**Comment by ghost** [comment]
:>>>>>> :D ❤️

**Comment by xcwen** [comment]
[test.tar.gz](https://github.com/xcwen/ac-php/files/1524573/test.tar.gz)


localhost:~/test$ php b.php 
1

you patch is wrong .


localhost:~/test$ cat a.php 
```php
<?php
function get_instance()
{
    return 1; 
}
```
localhost:~/test$ cat b.php
```php
<?php
namespace ss;
require("a.php");
class b  {
    function test() {
        echo get_instance();
    }
};
echo (new b())->test()."\n";
```

**Comment by xcwen** [comment]
sorry :< ,  it's a function , not class:>

**Comment by ghost** [comment]
@xcwen Hehe. That code is invalid, since the function in `a.php` is in the global namespace, and `b.php` is in the `\ss` namespace, which means that your code in `b.php` will try to look for `\ss\get_instance()`...

To make it valid, use `echo \get_instance()`, so that PHP will instead search for the global function. ;-)

By the way, your example code shows perfectly how PHPs class/function-finding algorithm works, and why my patch was important. Anything that uses a relative class/function path like that, will make PHP look inside the current file's namespace.

That is why my patch was important. If a path is global my patch scans globally, if not it always scans relatively. :-) So please keep that fixed code I submitted. It is correct and acts like PHPs algorithm.

**Comment by xcwen** [comment]
exec  php b.php . you will get "1", 
it's not invalid.

**Comment by ghost** [comment]
@xcwen Hmm you're right. PHP uses different rules for functions vs classes. I didn't know that. :-)

Here are the rules according to PHP's manual:

http://php.net/manual/en/language.namespaces.fallback.php

1. `Class names always resolve to the current namespace name.` = That's what my code patch did. Always resolve global `\Path` as global and relative `Path` _always_ as relative. (_Never_ look for a relative `Class` in the global `\Class`). Please be sure to keep my patch and never change that logic, because it's how PHP resolves classes. So it's important that AC-PHP uses the same logic as PHP. ;-)
2. `For functions and constants, PHP will fall back to global functions or constants if a namespaced function or constant does not exist.` = Aha. So for functions and constants, PHP _will_ try a global path if it cannot find it locally in the current namespace. So in your example, PHP first tries `\ss\get_instance()` and then if that's not found it instead tries `\get_instance()`.

So here's another example of how 2 is resolved:

```php
<?php
namespace ss;
require("a.php");
function get_instance() { return 'abc'; } // This is `\ss\get_instance()`!
class b  {
    function test() {
        echo get_instance()."\n"; // Tries local `\ss\get_instance()` and if fails it uses `\get_instance()`
        echo \get_instance()."\n"; // Uses `\get_instance()`
    }
};
echo (new b())->test()."\n";
```

Result: `abc` `1`. (If you remove the `\ss\get_instance()` function, both calls resolve to the global function from a.php and say `1 1` instead).

We learned something today: Functions are resolved differently than classes.

:>

**Comment by xcwen** [comment]
ok

**Comment by ghost** [comment]
xD

**Comment by xcwen** [comment]
fixed

**Comment by ghost** [comment]
https://github.com/xcwen/ac-php/commit/2c29113fbda6e2d76971290fb3b229e640a8776b

Yeah that looks excellent, great job. :) AC-PHP has really become great. With its new tag format (a nice single file) and all its fixes to autocompleting function args, multiline function definitions, multiline chaining calls, properly finding classes and functions, etc. Really great work. :>

**Comment by xcwen** [comment]
i'll copy it to readme :>
