### ISSUE TITLE
Question: globals

### ISSUE THREAD

**Issue by tworthington** [xcwen/ac-php#71]
Hi. As I've mentioned before, I work on Moodle projects. Moodle supplies several global objects (the database connection, the current page; some others). Taking the database as an example, it lives in $DB and is set up to whatever database you're using for a back end but with an abstract class which defines all the public functions. Is there any way I can define these globals in a file somewhere so that a function that has, say

`global $DB;`

at the start will allow me to use ac-php on $DB? I tried defining a stub file and simply putting

`<?php

$DB=moodle_database();
`

in it but it didn't seem to do anything for me.

**Comment by ghost** [comment]
Can't you do something like this whenever you want to auto-completion for that variable?

```php
global $DB;
/** @var \Moodle\DB $DB */
```

Replace `\Moodle\DB` with the right one and it should work?

**Comment by tworthington** [comment]
Apparently I can! Excellent. Thanks.

        /** @var moodle_database $DB **/
