### ISSUE TITLE
Bug (with fix inside): AC-PHP does not support PHP7 "self" keyword

### ISSUE THREAD

**Issue by aitte2** [xcwen/ac-php#73]
Hello again @xcwen 😄 

Here is a fix to make ac-php support PHP7 "self" keyword (many modern classes use that as return):

#### PHPCtags.class.php

Replace:

```php
    private function getRealClassName($className ,$scope  ){
        if ( $className=="\$this" ||  $className == "static"   ) {
```

Fixed version:

```php
    private function getRealClassName($className ,$scope  ){
        if ( $className=="\$this" || $className=="self" ||  $className == "static"   ) {
```

#### Test-file:

Test-file which shows the bug (to add this to ac-php's "a.php" or whatever your test files are named):

```php
<?php

namespace Bar;

class Foo
{
    public function retSelf(): self
    {
        return $this;
    }

    /**
     * @return $this
     */
    public function retThis()
    {
        return $this;
    }

    public function test(): self
    {
        // $this->retSelf() = OK
        // $this->retSelf()-> = BAD, "no find \Bar\self".
        // $this->retThis()-> = OK, finds "Foo" class.
    }
}
```

The comments above show what the unfixed PHPCTags generates. But the fix solves it. :)

This is the correct fix. I searched all sources and I tested this solution. Now "self" return value is treated as "$this" return value and mapped to the same class. Perfect! :)

**Comment by xcwen** [comment]
ok .
