### ISSUE TITLE
Support composer.json autoloading for completions

### ISSUE THREAD

**Issue by jlagneau** [xcwen/ac-php#76]
Currently, from what I can understand of the README, this package recommended way to find symbols in other file is to use a file `.ac-php-conf.json`. Is there any plan to use composer instead/in addition to that system for namespaces? A good support of PSR-0 and/or PSR-4 would greatly help for auto completion in modern PHP applications (especially for things like #72 ).

**Comment by xcwen** [comment]
how to ?!
