### ISSUE TITLE
add ignore file filter to .ac-php-conf.json

### ISSUE THREAD

**Issue by ghost** [xcwen/ac-php#77]
when i execute `ac-php-remake-tags-all` in my project, some error messages will log out, how about add a filter to the .ac-php-conf.json to ignore some files ?

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#configue-php-file-search-for-large-project

**Comment by ghost** [comment]
@xcwen yes, i know about the default filters，but if i want to ignore some files under a directory, not all of files of the directory, how do i config it? thanks

**Comment by xcwen** [comment]
```

{
  "filter": {
    "php-file-ext-list": [
      "php"
    ],
    "php-path-list": [
      "."
    ],
    "ignore-ruleset": [
      "# like .gitignore file ",
      "/vendor/**/[tT]ests/**/*.php"
    ]

  }
}
```
