### ISSUE TITLE
Duplicated % symbol when tags are regenerating.

### ISSUE THREAD

**Issue by ilyaguy** [xcwen/ac-php#78]
![2018-03-15 13 24 03](https://user-images.githubusercontent.com/6704355/37460540-287db318-2854-11e8-8b91-d6fa87ee362a.png)

**Comment by xcwen** [comment]
show me the  steps.

**Comment by ilyaguy** [comment]
1. Open PHP file inside big project. On small project/files it works too, but too quickly.
2. Run `M-x ac-php-remake-tags`
3. Look at modeline.

**Comment by xcwen** [comment]
not find :<
