### ISSUE TITLE
How to have company-mode complete for variables as well as functions?

### ISSUE THREAD

**Issue by cyrialize** [xcwen/ac-php#81]
This function works great, but when I have it set up (with using the config from melpa):
```
(add-hook 'php-mode-hook
         '(lambda ()
            (require 'company-php)
            (company-mode t)
            (add-to-list 'company-backends 'company-ac-php-backend )))
```

Company mode will only auto complete for php functions, not variables. I'd like to have both. For example I have the variable $password, when I start typing $p - I want the menu to have password, other words that start with p, _and_ php functions that start with p.

**Comment by xcwen** [comment]
it need more time to fix :> delay:>

**Comment by cyrialize** [comment]
Ah ok! Is the functionality that I described available for the auto-complete version?

**Comment by cyrialize** [comment]
I apologize for posting this issue - turns out there isn't an issue at all. I'm not sure what I had going on with my other config, but the code works perfectly! I'm now using the following so that the company-ac-php-backend is only used for php-mode:
```
(add-hook 'php-mode-hook
         '(lambda ()
            (require 'company-php)
            (company-quickhelp-mode)
            (set (make-local-variable 'company-backends)
                '(company-ac-php-backend))))
 
```
