### ISSUE TITLE
ac-php eldoc saying it is in the wrong class 

### ISSUE THREAD

**Issue by cyrialize** [xcwen/ac-php#83]
![ac-php-bug](https://user-images.githubusercontent.com/10124248/40065665-4b1037a0-5830-11e8-9983-1849cdea2958.PNG)

As shown in the above image, when using a "\" to refer to base PHP (i.e. outside of a namespace) ac-php's eldoc thinks that you are within \Exception.

**Comment by xcwen** [comment]
please  post the test.php .

**Comment by cyrialize** [comment]
Sure, it's literally this code:
```
<?php

$var = false;

if ($var === false) {
    throw new \Exception("$var cannot be false!");
}
```

Placing your cursor below the last bracket shows :\Exception in the mini buffer

**Comment by xcwen** [comment]
delay:<

**Comment by xcwen** [comment]
fixed
