### ISSUE TITLE
Is ac-php-find-symbol-at-point not support local variable yet?

### ISSUE THREAD

**Issue by algking** [xcwen/ac-php#84]
![image](https://user-images.githubusercontent.com/1456351/40909794-0af20e62-681d-11e8-80a1-a55a4c48f869.png)

I want to jump to de definition of the `$sessionToken`.
I found the code int the ac-php-core.el, but when I tried ac-php-find-symbol-at-point , nothing happend , so I turn on the debug mode.

![image](https://user-images.githubusercontent.com/1456351/40909873-4884a5f0-681d-11e8-93d9-ea239ead7b76.png)

I look into the code , It seems the tags.el did not have the sessionToken tag.

php version: php 7.2
emacs : emacs-mac 26.70

**Comment by xcwen** [comment]
retest

**Comment by algking** [comment]
I have the local variable $sessionToken in the function, But I can't find the keyword in the tags.el.

![image](https://user-images.githubusercontent.com/1456351/41010923-d45b6b72-696c-11e8-9c66-53d3eadf9240.png)

![image](https://user-images.githubusercontent.com/1456351/41010957-fda79c80-696c-11e8-9518-3175622088ca.png)

I retest again,  and remake the tags still the same.

**Comment by xcwen** [comment]
local variable 并不会生成到 tags.el 里.

**Comment by sergeyklay** [comment]
![image](https://user-images.githubusercontent.com/1256298/55836659-d9f3da80-5b27-11e9-99ab-c64f04cbc5fd.png)
