### ISSUE TITLE
interface extends complete error

### ISSUE THREAD

**Issue by OMGADE** [xcwen/ac-php#86]
above, can you help me? thanks!

**Comment by xcwen** [comment]
?!

**Comment by OMGADE** [comment]
Such as:
interface A{
function A();
}
interface B extends A{
function B();
}
then input "B::", result show only "B()" without "A()".

**Comment by xcwen** [comment]
ok .

**Comment by xcwen** [comment]
fixed , retest

**Comment by OMGADE** [comment]
good
