### ISSUE TITLE
Error with company

### ISSUE THREAD

**Issue by gjm** [xcwen/ac-php#88]
Hi, using company i get this error:

```
Company: An error occurred in auto-begin
Company: backend company-ac-php-backend error "Wrong type argument: hash-table-p, nil" with args (candidates cl)
```

Can you help me, please? Is there something i can do to help debug the issue?

Thanks in advance.

**Comment by xcwen** [comment]
https://github.com/xcwen/ac-php#faq

**Comment by sergeyklay** [comment]
Hello @gjm

I'm interested to fix this (or at least sorting it out). So, could you please help me? I'll need the steps to reproduce this on my laptop. Let's say I have a fresh installed Ubuntu with the vanilla Emacs without any package. What exactly should I do to get the same error?

Thank you.

**Comment by gjm** [comment]
Hello @sergeyklay 

I'm sorry but I can't really remember what I did to fix the issue since this happened some time ago... Probably a package upgrade solved it... Or maybe what is written in the FAQ pointed by @xcwen. 

I'm sorry I can't be of any more help.

Best regards.

**Comment by sergeyklay** [comment]
I'm closing this issue but if I have made an oversight, please do get back in touch. Thank you for the report, and for helping us make ac-php better!
