### ISSUE TITLE
no completion at all

### ISSUE THREAD

**Issue by jtkDvlp** [xcwen/ac-php#91]
Hi there,

help wanted please. I installed the package, remaked tags without error but got no completion, no system nor custom completion.

Triggering completion on custom class with `$this` gives message "no find xyz". But find symbol works fine. 

Triggering completion on e.g. `trim` does not work too.

It seems to me the tag generation does not work fine. There are only the following files but no el-files of custom classes etc.: `tag-file-map.json`, `tags.el`, `tags-cache-v2.json`

My config using emacs 25.3:
```
(use-package
  ac-php
  :demand t
  :init
  (defun enable-company-php ()
    (interactive)
    (ac-php-core-eldoc-setup)
    (make-local-variable 'company-backends)
    (add-to-list 'company-backends 'company-ac-php-backend))
  :hook (php-mode . enable-company-php))
```

**Comment by xcwen** [comment]
use company-php , not ac-php
```
(use-package
  company-php
  :demand t
  :init
  (defun enable-company-php ()
    (interactive)
    (ac-php-core-eldoc-setup)
    (make-local-variable 'company-backends)
    (add-to-list 'company-backends 'company-ac-php-backend))
  :hook (php-mode . enable-company-php))
```

https://github.com/xcwen/ac-php#usage-with-company

**Comment by jtkDvlp** [comment]
Ahh, it works. Stupid misstake :-$

Thank you!
